---
- name:  here comes the play
  hosts: myserver
  gather_facts: true
  vars:
    usersss:
      - ramu
      - somu
      - gomu

  tasks:
    - name: here come sthe variable
      user:
        name: "{{ item }}"
        state: absent
      with_items: "{{ usersss }}"      
...
        
