---
- name: Here is my first paly
  hosts: myserver
  tasks:
    - name: Installation of webserver
      yum: name=httpd
    - name: enable the server
      service: name=httpd enabled=true state=started
    - name: create the server file
      copy:
        content: "welcome to my server"
        dest: /var/www/html/index.html
        mode: 0777
    - name: open the firewall port
      firewalld:
        service: http
        state: enabled
        permanent: true
        immediate: yes
...
